[workspace]
resolver = "2"
members = [ "common", "odr-cmd", "odr-core", "odr-server"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
